"""your message

Revision ID: a357c0ab20a0
Revises: 
Create Date: 2025-01-31 16:49:37.589591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a357c0ab20a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_social', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('social_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'social_provider')
    op.drop_column('users', 'is_social')
    # ### end Alembic commands ###
